import = ["~/.config/alacritty/dracula.toml"]
# Shell configuration
[shell]
  program = "/bin/zsh"
  args =  [
"-c", "tmux new-session \\; run-shell '~/dotfiles/shellscripts/right_side_window.sh' \\; attach"]
[ env ]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font"

[window]
 
  option_as_alt = "Both"
  opacity = 0.90
  decorations = "none"
  blur = false
  position = { x = 749, y = 301 }
[window.dimensions]
  columns = 69
  lines = 43
# startup_mode = "Maximized"

