# import = ["~/.config/alacritty/dracula.toml"]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]
# Shell configuration
[shell]
  program = "/usr/local/bin/tmux"
  args = ["new-session"]
[ env ]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "FiraCode Nerd Font"

[window]
 
  option_as_alt = "Both"
  opacity = 0.8
  decorations = "Buttonless"
  blur = false
  # position = { x = 749, y = 301 }
[window.dimensions]
  # columns = 69
  # lines = 43
# startup_mode = "Maximized"

