#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/codes/web/react ~/codes/web/react/jagddish ~/codes/web  -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

cd "$selected"
# $SHELL
# nvim -c "lua require('telescope.builtin').find_files()"
nvim -c "lua require('oil').open()"
